[project]
site_url = "https://www.example.com/"
site_name = "Matemàtiques I"
# site_description = "Your project description"
# site_author = "Your name"

# copyright = "Copyright &copy; 2026 Your name"

# repo_url = "https://github.com/user/repo"
# repo_name = "user/repo"
# edit_uri = "edit/main/docs/"

nav = [
  { "Inici" = "index.md" },
  { "Nombres reals" = [{ "Introducció" = "nombres-reals/index.md" }, { "El conjunt dels nombres reals" = "nombres-reals/01_conjunt_nombres_reals.md" }, { "La recta real: relació d'ordre" = "nombres-reals/02_recta_real.md" }, { "Intervals i valor absolut" = "nombres-reals/03_intervals_valor_absolut.md" }, { "Aproximacions i errors" = "nombres-reals/04_aproximacions_errors.md" }, { "Potències" = "nombres-reals/05_potencies.md" }, { "Arrels i radicals" = "nombres-reals/06_arrels.md" }, { "Logaritmes" = "nombres-reals/07_logaritmes.md" }, { "Nota històrica" = "nombres-reals/08_nota_historica.md" }, { "Exercicis" = "nombres-reals/exercicis.md" }] },
  { "Àlgebra" = [{ "Introducció" = "algebra/index.md" }, { "Polinomis" = "algebra/01_polinomis.md" }, { "Factorització de polinomis" = "algebra/02_factoritzacio.md" }, { "Fraccions algebraiques" = "algebra/03_fraccions_algebraiques.md" }] },
  { "Equacions" = [{ "Introducció" = "equacions/index.md" }, { "Equacions polinòmiques" = "equacions/01_equacions_polinomiques.md" }, { "Equacions racionals i irracionals" = "equacions/02_equacions_racionals_irracionals.md" }, { "Equacions exponencials i logarítmiques" = "equacions/03_equacions_exponencials_logaritmiques.md" }, { "Nota històrica" = "equacions/04_nota_historica.md" }] },
  { "Geometria analítica" = [{ "Introducció" = "geometria/index.md" }, { "Vectors al pla" = "geometria/01_vectors.md" }, { "Sistema de referència i punts al pla" = "geometria/02_geometria_pla.md" }, { "Equacions de la recta" = "geometria/03_recta.md" }, { "Paral·lelisme i perpendicularitat" = "geometria/04_perpendicularitat i parallelisme.md" }, { "Posició relativa de dues rectes" = "geometria/05_posicio_rectes.md" }, { "Mètrica al pla" = "geometria/06_metrica_pla.md" }] },
  { "Anàlisi matemàtica" = [{ "Introducció" = "analisi/index.md" }, { "Funcions" = [{ "Concepte de funció. Domini i recorregut" = "analisi/01_concepte_funcio.md" }, { "Càlculs bàsics per trobar dominis" = "analisi/02_eines_calcul_dominis.md" }, { "Les funcions elementals" = "analisi/03_funcions_elementals.md" }, { "Transformacions de funcions" = "analisi/04_transformacio_funcions.md" }, { "Operacions amb funcions" = "analisi/05_operacions_funcions.md" }, { "Funcions en valor absolut" = "analisi/06_funcions_valor_absolut.md" }, { "Composició de funcions i funció inversa" = "analisi/07_composicio_inversa_funcions.md" }] }, { "Límits i continuïtat" = [{ "Concepte i càlcul de límits a infinit" = "analisi/08_limits_infinit.md" }, { "Concepte de límit en un punt" = "analisi/09_limits_punt.md" }, { "Continuïtat de funcions. Discontinuïtats" = "analisi/10_continuitat_discontinuitat.md" }, { "Càlcul de límits en un punt" = "analisi/11_calcul_limits_punt.md" }] }] },
]

# extra_css = ["stylesheets/extra.css"]
extra_javascript = [
  "javascripts/katex.js",
  "https://unpkg.com/katex@0/dist/katex.min.js",
  "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
]

extra_css = [
  "https://unpkg.com/katex@0/dist/katex.min.css",
  "stylesheets/extra.css",
]

[project.theme]
# variant = "classic"
# custom_dir = "overrides"
# favicon = "images/favicon.png"
language = "ca"
features = [
  "announce.dismiss",
  # "content.action.edit",
  # "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  # "navigation.instant.progress",
  "navigation.path",
  # "navigation.prune",
  "navigation.sections",
  "navigation.tabs",
  # "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  # "toc.follow",
  # "toc.integrate",
]

# logo = "assets/logo.png"

[project.theme.icon]
logo = "lucide/sigma"

# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/user/repo"

# [[project.extra.social]]
# icon = "fontawesome/brands/mastodon"
# link = "https://fosstodon.org/@user"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
tables = {}
toc = {
  permalink = true
}
pymdownx.arithmatex = {
  generic = true
}
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji = {
  emoji_generator = "zensical.extensions.emoji.to_svg",
  emoji_index = "zensical.extensions.emoji.twemoji",
}
pymdownx.highlight = {
  anchor_linenums = true,
  line_spans = "__span",
  pygments_lang_class = true,
}
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
# pymdownx.snippets = {
#   base_path = "includes",
# }
pymdownx.superfences = {
  custom_fences = [
    {
      name = "mermaid",
      class = "mermaid",
      format = "pymdownx.superfences.fence_code_format",
    },
  ],
}
pymdownx.tabbed = {
  alternate_style = true,
  combine_header_slug = true
}
pymdownx.tasklist = {
  custom_checkbox = true
}
pymdownx.tilde = {}
